name: "New Governance Problem Statement (GPS)"
description: "Propose a new Governance Problem Statement (GPS) for Cardano governance."
title: "GPS: [Short Title]"
labels: ["gps"]

body:
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Choose the governance category this GPS relates to.
      options:
        - Constitution
        - Governance
        - Delegation
        - Treasury
        - Voting
        - Meta
    validations:
      required: true

  - type: textarea
    id: authors
    attributes:
      label: Authors
      description: List all authors (Name <@GitHubHandle>).
      placeholder: "Alice <@alice>, Bob <@bob>"
    validations:
      required: false

  - type: textarea
    id: proposed_solutions
    attributes:
      label: Proposed Solutions (CAPs)
      description: List any related CAPs if they exist.
      placeholder: "CAP-0005"
    validations:
      required: false

  - type: textarea
    id: discussions
    attributes:
      label: Discussions
      description: Link to relevant discussion threads.
      placeholder: "https://github.com/Thomas-nada/CAP/discussions/XX"
    validations:
      required: false

  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: (~200 words) Summary of the governance problem.
    validations:
      required: false

  - type: textarea
    id: background
    attributes:
      label: Background
      description: Provide context and history of this governance problem.
    validations:
      required: false

  - type: textarea
    id: problem_description
    attributes:
      label: Problem Description
      description: Define the governance gap or ambiguity in detail.
    validations:
      required: false

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide stakeholder examples illustrating the problem.
    validations:
      required: false

  - type: textarea
    id: governance_goals
    attributes:
      label: Governance Goals
      description: List what ideal solutions should achieve.
    validations:
      required: false

  - type: textarea
    id: open_questions
    attributes:
      label: Open Questions
      description: List key governance questions any CAP should address.
    validations:
      required: false

  - type: textarea
    id: proposed_next_steps
    attributes:
      label: Proposed Next Steps (Optional)
      description: Suggest possible paths forward.
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References (Optional)
      description: Link related documents or resources.
    validations:
      required: false

  - type: textarea
    id: acknowledgements
    attributes:
      label: Acknowledgements (Optional)
      description: Credit contributors or reviewers.
    validations:
      required: false
