name: "New CAP Proposal"
description: "Submit a new Constitutional Amendment Proposal (CAP) for Cardano governance."
title: "CAP: [Short Title]"
labels: ["cap", "draft"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🧠 New CAP Proposal Form

        Thank you for contributing to Cardano governance!  
        This form will help you submit a **Cardano Amendment Proposal (CAP)** following the official process.

        🔎 **Important Notes:**
        - **CAP numbers** are assigned by editors during triage. Use `?` for the number when drafting.
        - Each CAP will be placed in its own folder named `CAP-XXXX/` with a `README.md` inside.
        - CAPs must address one or more [Governance Problem Statements (GPS)](./GPS-0001.md) if applicable.

  - type: input
    id: cap_title
    attributes:
      label: Title
      description: "A short, descriptive title for the amendment."
      placeholder: "Amendment to Clarify Constitutional Committee Accountability"

  - type: input
    id: authors
    attributes:
      label: Authors
      description: "List all authors in the format: Name <@GitHubHandle>"
      placeholder: "Ada Lovelace <@adalovelace>"

  - type: input
    id: implementors
    attributes:
      label: Implementors
      description: "List implementors or write N/A if not applicable."
      placeholder: "N/A"

  - type: input
    id: solution_to
    attributes:
      label: Solution-To (GPS)
      description: "Reference the Governance Problem Statement(s) this CAP addresses (e.g., GPS-0001). Leave blank if none."
      placeholder: "GPS-0003"

  - type: textarea
    id: discussions
    attributes:
      label: Discussions
      description: "Links to relevant GitHub discussions, forum threads, or PRs."
      placeholder: "- https://github.com/your-org/CAPs/discussions/123"

  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: "A concise (~200 words) summary of the amendment, the governance issue it addresses, and its intended outcome."
      placeholder: "Summarize the motivation for change, nature of the amendment, and intended outcomes."

  - type: textarea
    id: motivation
    attributes:
      label: Motivation: Why is this CAP necessary?
      description: "Explain the governance problem this amendment solves and how it improves outcomes. Reference linked GPS if applicable."
      placeholder: "Explain which stakeholders are affected, what problem is being solved, and why this change is necessary."

  - type: textarea
    id: specification
    attributes:
      label: Amendment Specification
      description: "Provide the **exact text** of the proposed constitutional change or addition."
      placeholder: |
        - New or updated constitutional text
        - Governance parameter changes
        - Definitions of new governance mechanisms
        - Versioning scheme (if applicable)

  - type: textarea
    id: rationale
    attributes:
      label: Rationale: How does this CAP achieve its goals?
      description: "Explain why this solution was chosen, trade-offs considered, community input, and backward compatibility (if applicable)."
      placeholder: "Explain the reasoning behind the proposal and why alternatives were rejected."

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Path to Ratification – Acceptance Criteria
      description: "Define the measurable conditions under which this amendment becomes **Active**."
      placeholder: |
        - Minimum vote thresholds and quorum
        - Constitutional Committee approval steps
        - Required governance actions
        - Compatibility with existing processes

  - type: textarea
    id: implementation_plan
    attributes:
      label: Implementation Plan
      description: "Outline how the amendment will be implemented once ratified."
      placeholder: |
        - Update the canonical constitution file
        - Execute an on-chain governance action
        - Coordinate off-chain communication
        - Notify tooling and governance participants

  - type: textarea
    id: versioning
    attributes:
      label: Versioning (Optional)
      description: "Describe how this amendment will be versioned or superseded in future governance processes."
      placeholder: "Optional – explain how future CAPs might replace or modify this one."

  - type: textarea
    id: references
    attributes:
      label: References (Optional)
      description: "List any relevant documentation, standards, governance decisions, or previous CAPs/GPSs referenced in this proposal."
      placeholder: |
        - GPS-0003
        - [Forum discussion](https://forum.cardano.org/t/example)
        - [CIP-0001](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0001)

  - type: markdown
    attributes:
      value: |
        ## 📜 Submission Checklist

        - [ ] I understand that CAP numbers are assigned by editors and will be replaced automatically.
        - [ ] I have structured my proposal following the CAP-0001 specification.
        - [ ] I have linked relevant Governance Problem Statements (GPS) where applicable.
        - [ ] I have included a clear Amendment Specification.
        - [ ] I agree that my submission will be licensed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode).
