name: Auto Label CAP and GPS PRs

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label CAP or GPS
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prTitle = context.payload.pull_request.title;
            const labels = [];

            if (prTitle.toUpperCase().includes("CAP-")) {
              labels.push("Type: CAP");
            }
            if (prTitle.toUpperCase().includes("GPS-")) {
              labels.push("Type: GPS");
            }

            // Always set draft as the default state
            labels.push("State: Draft");

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });
            }
