name: Sync Official Cardano Constitution

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Ensure we are on main
        run: |
          echo "📍 Current branch before switching:"
          git branch -a
          git checkout main || echo "⚠️ main branch already checked out or missing"
          echo "📍 Current branch after switching:"
          git branch -a

      - name: Download latest official constitution
        run: |
          mkdir -p constitution
          curl -L https://raw.githubusercontent.com/IntersectMBO/cardano-constitution/main/cardano-constitution-1/cardano-constitution-1.txt \
            -o constitution/constitution-v1.txt

          echo "✅ Download complete. First 10 lines:"
          head -n 10 constitution/constitution-v1.txt

      - name: Force stage and commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          echo "📂 Status BEFORE staging:"
          git status

          # Make sure git knows about any new files
          git add -A
          git update-index --refresh

          echo "📂 Status AFTER staging:"
          git status

          # Force a dummy change if nothing is detected (ensures commit runs)
          if git diff --cached --quiet; then
            echo "No changes detected – forcing a dummy commit to ensure sync."
            date > constitution/.last-sync
            git add constitution/.last-sync
          fi

          git commit -m "Sync: Update constitution from official source [auto]" || echo "✅ Nothing new to commit"
          git push origin main || echo "⚠️ Push skipped or failed"
