name: Create CAP folder and README from Issue

on:
  issues:
    types: [opened]

jobs:
  generate-cap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate CAP folder and README
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          CAP_NUMBER=$(printf "%04d" ${{ github.event.issue.number }})
          FOLDER="CAP-${CAP_NUMBER}"
          FILE_PATH="${FOLDER}/README.md"
          DATE=$(date +%Y-%m-%d)
          REPO_URL="https://github.com/Thomas-nada/CAP/tree/main"

          mkdir -p "$FOLDER"

          # ✅ Title from GitHub issue title
          TITLE="$ISSUE_TITLE"
          TITLE=$(echo "$TITLE" | sed -E 's/^CAP[: ]*//')

          echo "====== RAW ISSUE BODY ======"
          echo "$ISSUE_BODY"
          echo "============================"

          # ✅ Normalize the body to remove carriage returns
          NORMALIZED_BODY=$(echo "$ISSUE_BODY" | tr -d '\r')

          echo "====== NORMALIZED BODY ======"
          echo "$NORMALIZED_BODY"
          echo "============================="

          # ✅ Parse all fields with multiline-safe regex
          CATEGORY=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Category[^\n]*\n+([^\n#]+)/' | xargs)
          IMPLEMENTORS=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Implementors[^\n]*\n+([^\n#]+)/' | xargs)
          SOLUTION_TO=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Solution-To[^\n]*\n+([^\n#]+)/' | xargs)
          DISCUSSIONS=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Discussions[^\n]*\n+([^\n#]+)/' | xargs)
          ABSTRACT=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Abstract[^\n]*\n+([^\n#]+)/' | xargs)
          MOTIVATION=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Motivation[^\n]*\n+([^\n#]+)/' | xargs)
          SPECIFICATION=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Amendment Specification[^\n]*\n+([^\n#]+)/' | xargs)
          RATIONALE=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Rationale[^\n]*\n+([^\n#]+)/' | xargs)
          ACCEPTANCE=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Acceptance Criteria[^\n]*\n+([^\n#]+)/' | xargs)
          IMPLEMENTATION=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Implementation Plan[^\n]*\n+([^\n#]+)/' | xargs)
          VERSIONING=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /Versioning[^\n]*\n+([^\n#]+)/' | xargs)
          REFERENCES=$(echo "$NORMALIZED_BODY" | perl -0777 -ne 'print $1 if /References[^\n]*\n+([^\n#]+)/' | xargs)

          # ✅ Fallbacks
          [ -z "$CATEGORY" ] && CATEGORY="Governance"
          [ -z "$IMPLEMENTORS" ] && IMPLEMENTORS="_No response_"
          [ -z "$SOLUTION_TO" ] && SOLUTION_TO="N/A"
          [ -z "$DISCUSSIONS" ] && DISCUSSIONS="_No response_"
          [ -z "$ABSTRACT" ] && ABSTRACT="No response"
          [ -z "$MOTIVATION" ] && MOTIVATION="No response"
          [ -z "$SPECIFICATION" ] && SPECIFICATION="No response"
          [ -z "$RATIONALE" ] && RATIONALE="No response"
          [ -z "$ACCEPTANCE" ] && ACCEPTANCE="No response"
          [ -z "$IMPLEMENTATION" ] && IMPLEMENTATION="No response"
          [ -z "$VERSIONING" ] && VERSIONING="No response"
          [ -z "$REFERENCES" ] && REFERENCES="No response"

          # 🧠 Smart linking for Solution-To
          if [[ "$SOLUTION_TO" =~ ^GPS-[0-9]+$ ]]; then
            SOLUTION_TO_MARKDOWN="[${SOLUTION_TO}](${REPO_URL}/${SOLUTION_TO})"
          else
            SOLUTION_TO_MARKDOWN="$SOLUTION_TO"
          fi

          # 🧠 Smart linking for Discussions
          if [[ "$DISCUSSIONS" =~ ^https?:// ]]; then
            DISCUSSIONS_MARKDOWN="$DISCUSSIONS"
          else
            DISCUSSIONS_MARKDOWN="$DISCUSSIONS"
          fi

          echo "📎 Parsed Solution-To: $SOLUTION_TO"
          echo "📎 Final link: $SOLUTION_TO_MARKDOWN"

          # ✅ Write README.md
          echo "---" > "$FILE_PATH"
          echo "CAP: ${CAP_NUMBER}" >> "$FILE_PATH"
          echo "Title: \"${TITLE}\"" >> "$FILE_PATH"
          echo "Category: ${CATEGORY}" >> "$FILE_PATH"
          echo "Status: Draft" >> "$FILE_PATH"
          echo "Authors:" >> "$FILE_PATH"
          echo "  - TBD" >> "$FILE_PATH"
          echo "Implementors:" >> "$FILE_PATH"
          echo "  - ${IMPLEMENTORS}" >> "$FILE_PATH"
          echo "Solution-To:" >> "$FILE_PATH"
          echo "  - ${SOLUTION_TO_MARKDOWN}" >> "$FILE_PATH"
          echo "Discussions:" >> "$FILE_PATH"
          echo "  - ${DISCUSSIONS_MARKDOWN}" >> "$FILE_PATH"
          echo "Created: ${DATE}" >> "$FILE_PATH"
          echo "License: CC-BY-4.0" >> "$FILE_PATH"
          echo "---" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"

          echo "## Abstract" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"
          echo "${ABSTRACT}" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"

          echo "## Motivation: Why is this CAP necessary?" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"
          echo "${MOTIVATION}" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"

          echo "## Amendment Specification" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"
          echo "${SPECIFICATION}" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"

          echo "## Rationale: How does this CAP achieve its goals?" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"
          echo "${RATIONALE}" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"

          echo "## Path to Ratification" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"
          echo "### Acceptance Criteria" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"
          echo "${ACCEPTANCE}" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"

          echo "### Implementation Plan" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"
          echo "${IMPLEMENTATION}" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"

          echo "## Versioning (Optional)" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"
          echo "${VERSIONING}" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"

          echo "## References (Optional)" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"
          echo "${REFERENCES}" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"

          echo "## Copyright" >> "$FILE_PATH"
          echo "" >> "$FILE_PATH"
          echo "This CAP is licensed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode)." >> "$FILE_PATH"

      - name: Commit and push CAP folder
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add CAP-${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          file_pattern: "CAP-*/*"
