name: Create CAP Markdown from Issue
on:
  issues:
    types: [opened]

jobs:
  generate-cap:
    if: contains(github.event.issue.labels.*.name, 'cap')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate CAP markdown
        run: |
          mkdir -p CAPs
          FILENAME="CAPs/CAP-${{ github.event.issue.number }}.md"
          cat > $FILENAME <<EOF
---
CAP: ${{ github.event.issue.number }}
Title: ${{ github.event.issue.title }}
Status: Draft
Created: $(date +%Y-%m-%d)
License: CC-BY-4.0
---

${{ github.event.issue.body }}
EOF

      - name: Commit CAP file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add CAP ${{ github.event.issue.number }}"
          file_pattern: CAPs/*.md
