name: generate-gps

on:
  issues:
    types: [opened]

jobs:
  generate-gps:
    if: startsWith(github.event.issue.title, 'GPS:') || startsWith(github.event.issue.title, 'New GPS')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set GPS number (ignore GPS-9999)
        id: gps_number
        run: |
          COUNT=$(find . -type d -name "GPS-*" | grep -v "GPS-9999" | wc -l)
          NEXT=$(printf "%04d" $((COUNT + 1)))
          echo "GPS_NUMBER=$NEXT" >> $GITHUB_ENV

      - name: Create new GPS folder and README.md
        run: |
          mkdir -p GPS-${{ env.GPS_NUMBER }}
          cat > GPS-${{ env.GPS_NUMBER }}/README.md << 'EOF'
---
GPS: ${{ env.GPS_NUMBER }}
Title: "${{ github.event.issue.title }}"
Category: Governance
Status: Open
Authors:
  - TBD
Proposed Solutions:
  - "_No response_"
Discussions:
  - "_No response_"
Created: $(date +'%Y-%m-%d')
License: CC-BY-4.0
---

## Abstract

_No response_

## Background

_No response_

## Problem Description

_No response_

## Use Cases

_No response_

## Governance Goals

_No response_

## Open Questions

_No response_

## Proposed Next Steps (Optional)

_No response_

## Status

Open

## References (Optional)

_No response_

## Acknowledgements (Optional)

_No response_

## Copyright

This GPS is licensed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode).
EOF

      - name: Commit and push GPS
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add GPS-${{ env.GPS_NUMBER }} - ${{ github.event.issue.title }}"
          file_pattern: GPS-*/*
