name: Auto-update CAP/CIS Index
on:
  push:
    branches:
      - Automatic-indexing
    paths:
      - 'CAP-*/*.md'
      - 'CIS-*/*.md'

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update CAP/CIS Index
        run: |
          python .github/scripts/update_index.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && echo "No changes to commit" || git commit -m "🔁 Auto-update CAP/CIS index"
          git push
