name: Auto-update CAP/CIS Index

on:
  push:
    branches:
      - '**'      # Allow running on any branch for testing; change to 'main' later
    paths:
      - 'CAP-*/*.md'
      - 'CIS-*/*.md'

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir PyYAML

      - name: Run index updater
        shell: bash
        run: |
          python .github/scripts/update_index.py

      - name: Commit and push updates
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🔁 Auto-update CAP/CIS index"
            # Fetch the latest branch state and rebase before pushing
            git fetch origin $GITHUB_REF_NAME
            git rebase origin/$GITHUB_REF_NAME
            git push origin HEAD:$GITHUB_REF_NAME
          fi
