name: Auto-generate CAP & GPS Index

on:
  push:
    branches: [ main ]
  workflow_dispatch: # allow manual runs too

permissions:
  contents: write   # ✅ REQUIRED for git push to work

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      # 4. Run the index generation script
      - name: Generate CAP & GPS index
        run: python .github/scripts/generate_index.py

      # 5. Commit & push changes (if any)
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md || true
          git diff --cached
