name: Auto-generate CAP & GPS Index

on:
  push:
    branches: [ main ]
  workflow_dispatch: # allow manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run index generator
        run: python .github/scripts/generate_index.py

      - name: Commit and push updated README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md || true
          git diff --cached --quiet && echo "No changes detected — skipping commit." || git commit -m "chore: auto-update CAP/GPS index"
          git push
